name: Generic Package CI
on: push

jobs:
  build:

    runs-on: grouptech-actions-runners

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm run-script test-ci

    - run: npm run-script build-ci okta_native
    - run: test -f distributions/okta_native/okta_native.zip
    - run: npm run-script build-ci rotate_key_pair
    - run: test -f distributions/rotate_key_pair/rotate_key_pair.zip

    - uses: actions/upload-artifact@v4
      with:
        name: packages_${{ matrix.node-version }}
        path: distributions/*/*.zip
